name: Submit to CodeSpell
on:
  push:
    branches:
      - main

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v1

      - name: Submit to CodeSpell
        uses: code-spell/codespell-submission-action@91c41516bb441ced971378e4adaf055903370ee4
        with:
          content-id: ${{ vars.CODESPELL_CONTENT_ID }}
          language: JAVA
          username: ${{ secrets.CODESPELL_USER_ID }}
          password: ${{ secrets.CODESPELL_AUTH_TOKEN }}
